services:
  # if a Prolific user returns a task, this cron job ensures that the task is added back to the pool of available tasks.
  - type: cron
    name: return-tasks
    runtime: python
    schedule: "0 * * * *"
    startcommand: python return_tasks.py